name: Pull Request CI

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  lint:
    name: "Check project by lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: lint
        run: ./gradlew lint
  ktlint:
    name: "Check project by ktlint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: ktlint
        run: ./gradlew ktlintCheck
